### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by kunchiehw** [kunchiehw/bidding_box#4]
The current naming for the folders and files are not clear enough. Should redesign the naming.

**Comment by kunchiehw** [comment]
room-interface
  - RoomInterface.jsx
  - util
    - Util.jsx
  - bid_buttons
    - BidButtons.jsx
    - SuitBidButton.jsx
    - OtherBidButton.jsx
  - bid_sequence_display
    - BidSequenceDisplay.jsx
    - SeatBlock.jsx
      -SeatCell
    - BidBlock.jsx
      - BidRow
      - BidCell
  - hand_cards_display
    - HandCardsDisplay.jsx
  - tool_buttons
    - LeaveButton.jsx
    - UndoButton.jsx

**Comment by jarronshih** [comment]
- move utils outside
- change pure js file to `*.js` (ex: `Utils.jsx` to `utils.js`)
- use singular instead of plurals

**Comment by jarronshih** [comment]
If this is completed, we could close the issue.

**Comment by kunchiehw** [comment]
Finish implementing.
